import type {Metadata} from "next";
import localFont from "next/font/local"
import "./globals.css";
import {cn} from "@/lib/utils";


const myFont = localFont({
    src: [
        {path: "../public/fonts/IosevkaNerdFontMono-Regular.woff2", weight: '400', style: 'normal'},
        {path: "../public/fonts/IosevkaNerdFontMono-Medium.woff2", weight: '500', style: 'normal'},
        {path: "../public/fonts/IosevkaNerdFontMono-Bold.woff2", weight: '700', style: 'normal'},
    ],
    variable: '--font-mono',
    display: 'swap',
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn("h-full", "antialiased", myFont.variable, "font-sans")}
        >
        <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
